/// Flutter icons Humidity
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
//    - family:  Humidity
//      fonts:
//       - asset: fonts/Humidity.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Humidity {
  Humidity._();

  static const _kFontFam = 'Humidity';

  static const IconData humidity = const IconData(0xe800, fontFamily: _kFontFam);
}
